/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    BreadcrumbsBar: typeof import('./src/components/molecules/BreadcrumbsBar.vue')['default']
    Button: typeof import('primevue/button')['default']
    ButtonCart: typeof import('./src/components/atoms/ButtonCart.vue')['default']
    CartProductActions: typeof import('./src/components/atoms/CartProductActions.vue')['default']
    CartProductCard: typeof import('./src/components/molecules/CartProductCard.vue')['default']
    CartStep: typeof import('./src/components/organisms/CartStep.vue')['default']
    CheckoutPage: typeof import('./src/components/pages/CheckoutPage.vue')['default']
    DataView: typeof import('primevue/dataview')['default']
    Drawer: typeof import('primevue/drawer')['default']
    FavoriteButton: typeof import('./src/components/atoms/FavoriteButton.vue')['default']
    GridProductCard: typeof import('./src/components/molecules/GridProductCard.vue')['default']
    HeaderRight: typeof import('./src/components/atoms/HeaderRight.vue')['default']
    HeaderToolbar: typeof import('./src/components/organisms/HeaderToolbar.vue')['default']
    HomePage: typeof import('./src/components/pages/HomePage.vue')['default']
    Image: typeof import('primevue/image')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    ListProductCard: typeof import('./src/components/molecules/ListProductCard.vue')['default']
    LocaleSwitcher: typeof import('./src/components/atoms/LocaleSwitcher.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    MultiSelectFilter: typeof import('./src/components/atoms/MultiSelectFilter.vue')['default']
    OverlayBadge: typeof import('primevue/overlaybadge')['default']
    Panel: typeof import('primevue/panel')['default']
    Popover: typeof import('primevue/popover')['default']
    ProductActions: typeof import('./src/components/atoms/ProductActions.vue')['default']
    ProductCardSkeleton: typeof import('./src/components/molecules/ProductCardSkeleton.vue')['default']
    ProductDetailsPage: typeof import('./src/components/pages/ProductDetailsPage.vue')['default']
    ProductFiltersPanel: typeof import('./src/components/organisms/ProductFiltersPanel.vue')['default']
    ProductList: typeof import('./src/components/organisms/ProductList.vue')['default']
    ProductRating: typeof import('./src/components/atoms/ProductRating.vue')['default']
    RangeFilter: typeof import('./src/components/atoms/RangeFilter.vue')['default']
    Rating: typeof import('primevue/rating')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/organisms/SearchBar.vue')['default']
    SearchProductCard: typeof import('./src/components/molecules/SearchProductCard.vue')['default']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Slider: typeof import('primevue/slider')['default']
    Step: typeof import('primevue/step')['default']
    StepList: typeof import('primevue/steplist')['default']
    StepPanel: typeof import('primevue/steppanel')['default']
    StepPanels: typeof import('primevue/steppanels')['default']
    Stepper: typeof import('primevue/stepper')['default']
    Tag: typeof import('primevue/tag')['default']
    Toast: typeof import('primevue/toast')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
